# Generated by Django 4.2.3 on 2023-07-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_enrollstudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnrollStudent',
        ),
    ]
